### PR TITLE
Drag n drop

### PR DESCRIPTION
**Pull request by yuzu-r**
Drag and drop enabled for moving pieces.
@jonianven, I don't know why, but moving a king to make a castle was giving me invalid move. I had a gnarly merge so can you check if I left something out by accident?

### CODE REVIEW

**Comment by jonianven** [comment]
@yuzu-r Any instances of game.is_in_check?(player) & will_be_in_check?(dest_x, dest_y) in king.rb are keeping castling from happening, which is strange, since I thought I fixed those methods (comment them out and you can see castling work). 

What's even more perplexing is how castling keeps passing in rspec as if these methods are working already... I don't think anything you did in drag-n-drop is causing this.

**Comment by yuzu-r** [comment]
@jonianven ok, will merge & I'll take another look is_in_check? & will_be_in_check? today. Thanks.

**Comment by yuzu-r** [comment]
I think the methods are ok since they are passing & the tests look fine. The issue is that the js doesn't recognize the castle move (castleMove is false when I move the king 2 spaces over).

**Comment by jonianven** [comment]
@yuzu-r : were you testing black? i now realize it is only returning true for white pieces                         `selectedPiece.html().indexOf('♔') === 0`

i should add -- 
                      `selectedPiece.html().indexOf('♚') === 0`
as well. can you try is_in_check? and will_be_in_check? in the rails console? they were calling methods on nilclass yesterday and producing errors that way...

**Comment by yuzu-r** [comment]
Yes.. I was testing black. :)
Although white recognizes as a castle move, it still gives me invalid move in the end. hmm

**Comment by yuzu-r** [comment]
I see in the console it is will_be_in_check? returning true if I try to do is_valid_castle? (7,1).

**Comment by jonianven** [comment]
var castleMove in the show page shouldn't prevent the move from actually happening... it's just there to manually move the rook after the post callback so you don't have to refresh the page to see the castle. in my environment i can't get those check methods to work at all, let alone return true or false

?_?

**Comment by yuzu-r** [comment]
hmm.. in the console? here's what I'm doing:
irb(main):006:0> p2=Piece.find(300)
irb(main):007:0> p2.will_be_in_check?(7,1)
(stuff outputs)
=> true

Also I discovered, if you change the model to put logger messages in, you can do reload! and then if you create a new object, like p3=Piece.find(300), p3 will have the newly changed method. Rather than quit the console and starting over. 

This is tricky, not sure what is going on. I'm back to believing it's the model.

**Comment by jonianven** [comment]
Yep, I've been doing that too... Still no luck. I might just clone the repo to see if it fixes whatever's wrong locally. And that's a neat trick, thanks :) 

Hope we figure this one out soon. On the plus side, I tried en passant with drag n drop and it works like a charm.

**Comment by yuzu-r** [comment]
oookkk. I found the problem, at least the one I was having...
The issue is that game.black_player.pieces returns all pieces everywhere owned by the black player... NOT restricted by the game. To restrict by the current game, I had to do
game.black_player.pieces.where(game: game, is_active: true)
I actually saw the drag & drop castle work after I changed this!

This probably won't come up in tests because FactoryGirl is creating a new user each time. So they have no other games where pieces can interfere.

**Comment by jonianven** [comment]
Ohh! Explains my problem too. I had some deleted db entries associated with the player. Awesome work!

Would you like to do the pull request for this bug since you found it? If you do don't forget in show.html -- 
`var castleMove` should include in its logic
`(selectedPiece.html().indexOf('♔') === 0 || selectedPiece.html().indexOf('♚') === 0)`

**Comment by yuzu-r** [comment]
Ok, I'll get both fixes in shortly.

**Pull request merged**
